# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO_REST_VERSION=3.3.3
  - DJANGO_REST_VERSION=3.2.5
  - DJANGO_REST_VERSION=3.1.3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q djangorestframework==$DJANGO_REST_VERSION
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: python runtests.py